### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by the-WD40** [infofiend/GCal-Search#1]
Would it be possible to make the offset time adjustable in WebCore?  I would like to use an algorithm to set how early a set of thermostats turn on prior to an event.   The time can be in any format, miniutes, seconds, milliseconds, etc...

Btw, thank you for your work.

**Comment by infofiend** [comment]
check out new gCal Event Sensor 20180327.2 
- added startOffset and endOffset attributes;
- these can be set by new commands setStartoffset() and setEndoffset() 
**Keep in mind that if you modify these attribute(s), they will always override the offSets in the gCal Trigger parent app!)**
